### ISSUE TITLE
duplicate entries in event log

### ISSUE THREAD

**Issue by dubslow** [glinscott/fishtest#1547] opened 2023-01-20 02:25 UTC
23‑01‑20 02:18:15    finished_run    Vizvezdenec    mcpTtcaptL2-ba0e5fd    Result:red Elo:-0.76[-2.15,0.65] LOS:14% Games:25416 Ptnml:[18,5172,15167,5043,16]
    23‑01‑20 02:13:38    finished_run    Vizvezdenec    mcpTtcaptL2-ba0e5fd    Result:red Elo:-0.75[-2.14,0.65] LOS:15% Games:25412 Ptnml:[18,5170,15165,5043,16]

I think it's reporting the game count incorrectly, perhaps as pairs, not games, compare the actual stats from the test page:

    Total: 50832 W: 13375 L: 13508 D: 23949
    Ptnml(0-2): 18, 5172, 15167, 5043, 16```

https://tests.stockfishchess.org/tests/view/63c7059e18c20f4929c63833

**Comment by vdbergh** [comment] 2023-01-20 05:21
😦 … I’ll fix it.

**Comment by vdbergh** [comment] 2023-01-20 07:25
Actually I am noticing you are pointing out two problems. The issue of duplicate entries in the event log is much more serious. It points to a race condition in the server.

The `finished_run` event is created by `update_task` which acquires a lock... The `finished_run` event is only generated after checking that the run is really finished.

The two `finished_run` events were five minutes apart.

Nothing happened between the two `finished_run` events:

https://tests.stockfishchess.org/actions?run_id=63c7059e18c20f4929c63833

The issue must be that `update_task` does not check if a run is already finished. However if does check that the current task is active. And if a run is stopped all tasks are set to non-active.

But conceivably a worker may request a new task while a run is being stopped in `update_task`. If I am reading the code correctly then `request_task` does not acquire the same lock as `update_task` (presumably because normally they don't interfere).

**Comment by dubslow** [comment] 2023-01-20 07:43
My basic assumption would be that some task which started before the run finished then later the task after the run ended. If I understand you right, your second-to-last paragraph says this couldn't be the cause, since "late" task results are ignored, but your last paragraph says that somehow one last task was assigned right as the run ended the first time, in an unlikely-but-plausible race condition? That would be funny lol. But as you say, if this is so, then the fix should be as simple as making `request_task` get the same lock.

**Comment by vdbergh** [comment] 2023-01-20 07:50
>  But as you say, if this is so, then the fix should be as simple as making `request_task` get the same lock.

Yeah basically, but currently this will deadlock, so it requires a bit of thought.

**Comment by dubslow** [comment] 2023-01-20 07:59
github "bug" lol, this issue isn't solved yet

**Comment by ppigazzini** [comment] 2023-01-20 08:07
GitHub closes automatically an issue if referenced with any variation of the keywords "close", "fix", "resolve" in a merged PR. I'm on mobile right now.

**Comment by ppigazzini** [comment] 2023-01-20 17:57
Let's view if the problem is solved. Thank you @dubslow for the report :)

**Closed** 2023-01-20 21:20 UTC
