### ISSUE TITLE
Fishtest down

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#935] opened 2021-05-29 07:47 UTC
Fishtest seems to be going down occasionally recently. I wonder if it is an assertion failure in my latest PR. @ppigazzini Can you check this is in the logs?

**Comment by ppigazzini** [comment] 2021-05-29 07:57
mongod was down, I'm checking the logs.

**Comment by ppigazzini** [comment] 2021-05-29 08:22
No asserts in fishtest logs, only pymongo errors after mongod went down. I don't found anything in mongod logs, no logs about OOM killer.

@tomtor I don't know if it's ok to have countless messages of this type:
```
sudo journalctl -u fishtest@6543 --since "5 minutes ago"

-- Logs begin at Mon 2021-05-24 10:31:48 UTC, end at Sat 2021-05-29 08:19:46 UTC. --
May 29 08:14:51 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1dea887a1a67ae56c48d1 11 Garruk-2cores-1
May 29 08:15:02 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b12e7c87a1a67ae56c4804 400 Garruk-2cores
May 29 08:15:12 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1759587a1a67ae56c4855 469 Garruk-2cores-1
May 29 08:15:23 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1de1587a1a67ae56c48c8 33 Garruk-2cores
May 29 08:15:37 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1b77587a1a67ae56c4882 165 AndreasKrug-1cores-27
May 29 08:15:40 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1dede87a1a67ae56c48dd 10 Garruk-2cores-1
May 29 08:15:44 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1def087a1a67ae56c48e1 9 Garruk-2cores
May 29 08:16:02 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1dea187a1a67ae56c48cf 9 Garruk-2cores-1
May 29 08:16:05 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1c48587a1a67ae56c488d 110 Garruk-2cores
May 29 08:16:06 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1c48587a1a67ae56c488d 108 AndreasKrug-1cores-28
May 29 08:16:22 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df2b87a1a67ae56c48ec 11 Garruk-2cores-1
May 29 08:16:26 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b13dc087a1a67ae56c4814 857 Garruk-2cores
May 29 08:16:27 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df2b87a1a67ae56c48ec 10 AndreasKrug-1cores-29
May 29 08:16:44 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60aed05012066fd299795ae0 1996 Garruk-2cores-1
May 29 08:16:47 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1b7d387a1a67ae56c4884 188 Garruk-2cores
May 29 08:17:05 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1b7d387a1a67ae56c4884 188 Garruk-2cores-1
May 29 08:17:08 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1b7d387a1a67ae56c4884 191 Garruk-2cores
May 29 08:17:26 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1de9287a1a67ae56c48cb 9 Garruk-2cores-1
May 29 08:17:29 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1de9287a1a67ae56c48cb 11 Garruk-2cores
May 29 08:17:47 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df2b87a1a67ae56c48ec 10 Garruk-2cores-1
May 29 08:17:50 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df2b87a1a67ae56c48ec 11 Garruk-2cores
May 29 08:18:08 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1deae87a1a67ae56c48d3 12 Garruk-2cores-1
May 29 08:18:11 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1759587a1a67ae56c4855 470 Garruk-2cores
May 29 08:18:29 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1759587a1a67ae56c4855 470 Garruk-2cores-1
May 29 08:18:31 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1cfba87a1a67ae56c489d 64 Garruk-2cores
May 29 08:18:51 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1def087a1a67ae56c48e1 9 Garruk-2cores-1
May 29 08:18:52 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1def087a1a67ae56c48e1 11 Garruk-2cores
May 29 08:19:13 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df2b87a1a67ae56c48ec 11 Garruk-2cores-1
May 29 08:19:13 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1dbe087a1a67ae56c48be 31 Garruk-2cores
May 29 08:19:34 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df0187a1a67ae56c48e5 11 Garruk-2cores-1
May 29 08:19:34 tests.stockfishchess.org pserve[32488]: Inactive: https://tests.stockfishchess.org/tests/view/60b1df0187a1a67ae56c48e5 12 Garruk-2cores
```

**Comment by ppigazzini** [comment] 2021-05-29 08:35
@vondele @tomtor @vdbergh @snicolet I'm stopping fishtest for some minutes to compact the mongodb collections.

**Comment by vondele** [comment] 2021-05-29 08:37
sure

**Comment by ppigazzini** [comment] 2021-05-29 08:41
Done, only down for a dozen of seconds, way faster than I remembered :)

**Comment by vondele** [comment] 2021-05-29 08:53
you think that might have fixed the cause of the mongod crash?

**Comment by ppigazzini** [comment] 2021-05-29 09:04
No, this help only to free some disk space.

**Comment by xoto10** [comment] 2021-05-30 07:04
Is it possible the tuning runs are contributing?

**Comment by ppigazzini** [comment] 2021-05-30 07:28
Restarted mongod with lowered `cacheSizeGB: 1.25`

In the last two days `mongod` was killed just after the start of `delta_update_users.py`, here `syslog`:

```
May 29 07:01:01 tests CRON[30870]: (fishtest) CMD (${VENV}/bin/python3 ${UPATH}/delta_update_users.py)
May 29 07:01:02 tests pserve[294]: Inactive: https://tests.stockfishchess.org/tests/view/60b1cfba87a1a67ae56c489d 56 Garruk-2cores-1
May 29 07:01:03 tests pserve[294]: Inactive: https://tests.stockfishchess.org/tests/view/60b1794487a1a67ae56c485b 493 Garruk-2cores
May 29 07:01:26 tests systemd[1]: mongod.service: Main process exited, code=killed, status=9/KILL
May 29 07:01:26 tests systemd[1]: mongod.service: Failed with result 'signal'.
May 29 07:01:26 tests pserve[294]: Flush exception
May 29 07:01:26 tests pserve[298]: 2021-05-29 07:01:26,587 ERROR [waitress][waitress-3] Exception while serving /tests/user/vdv
May 29 07:01:26 tests pserve[298]: Traceback (most recent call last):


May 30 06:16:01 tests CRON[10958]: (fishtest) CMD (${VENV}/bin/python3 ${UPATH}/delta_update_users.py)
May 30 06:16:28 tests pserve[3691]: Flush exception
May 30 06:16:28 tests systemd[1]: mongod.service: Main process exited, code=killed, status=9/KILL
May 30 06:16:28 tests pserve[3690]: 2021-05-30 06:16:28,772 ERROR [waitress][waitress-3] Exception while serving /api/upload_pgn
May 30 06:16:28 tests pserve[3690]: Traceback (most recent call last):
```

**Comment by tomtor** [comment] 2021-05-30 14:39
> I don't know if it's ok to have countless messages of this type:

@ppigazzini It's just an indication that some workers are behaving in a strange way, most probably they are hard killed, so they have no opportunity to sign off. Please feel free to remove/comment the logging line.

These log lines are not written to mongoDB.

**Comment by ppigazzini** [comment] 2021-05-30 15:06
Two weeks ago I configured PROD with python 3.9.5, the 2 server processes used 46.5% of RAM. Now with python 3.8.10 the server processes are using 39.8% of RAM. This difference perhaps was sufficient to trigger the OOM killer. I keep monitoring the RAM usage.

**Comment by ppigazzini** [comment] 2021-06-01 08:42
I'm closing this issue.
Definitively my fault :(
With  mongodb `cacheSizeGB: 1.75` python 3.8.10 is using only 34%.
Updated the wiki server setup script.

```
20420 mongodb   20     3684480 2.040g   5340 S   2.1 40.8  45:34.77  `- /usr/bin/mongod --config /etc/mongod.conf
20460 fishtest  20     2302276 1.293g   6660 S  14.8 25.9 398:59.20  `- /home/fishtest/fishtest/server/env/bin/python3 /home/fishtest/fishtest/server/env/bin/pserve production.ini http_port=6543
20461 fishtest  20     1242772 420156   6512 S        8.0  19:05.38  `- /home/fishtest/fishtest/server/env/bin/python3 /home/fishtest/fishtest/server/env/bin/pserve production.ini http_port=6544
```

**Closed by ppigazzini** 2021-06-01 08:42 UTC

**Comment by vondele** [comment] 2021-06-01 08:56
Thanks for figuring it out!
