### ISSUE TITLE
Residual shown for terminated worker

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#1031] opened 2021-09-14 16:22 UTC
After restarting my 14 core worker, the residual is shown and updated with the terminated worker, not the active one (task 595):

![Screenshot from 2021-09-14 18-18-23](https://user-images.githubusercontent.com/1104260/133295815-2c2f48f1-dd05-40c4-96e7-7ec1d18d8ea9.png)

**Comment by ppigazzini** [comment] 2021-09-14 16:34
If I'm not wrong:
- the worker changed UUID
- the new worker UUID had not played the number of games to fulfill this chi2 requirement
https://github.com/glinscott/fishtest/blob/760771478f377cfac08fa98219c220bd188a8ec0/server/fishtest/util.py#L107-L110

**Comment by vdbergh** [comment] 2021-09-14 16:56
I had a look but for now I don't see how it is possible. It must be a race condition but I don't see how.

**Comment by vdbergh** [comment] 2021-09-14 16:59
Could you perhaps post the link to the test page?

**Comment by tomtor** [comment] 2021-09-14 17:10
https://tests.stockfishchess.org/tests/view/61403a377315e7c73204a4b6

**Comment by vdbergh** [comment] 2021-09-14 17:53
But it seems that this worker had already done task 425. So there is no issue.

Or do we have case where two workers got the same worker key?

**Comment by ppigazzini** [comment] 2021-09-14 18:37
The last digit group in the worker name is the first digit group in the worker key (uuid.txt), the two worker have different keys.

We have an open issue #878 about a worker getting other user heartbeat, not investigated but that could be due to the reassignment of unfinished tasks.

**Comment by vdbergh** [comment] 2021-09-14 18:43
Yes but the chi2 table is made by worker key, i.e. the key that is displayed on the main page. This has always been the case. I did not change this.

**Comment by vdbergh** [comment] 2021-09-14 19:02
I think the code is working as designed (but perhaps the design should be changed). 

But orthogonal to this: it seems rather unlikely that two randomly generated 32 bit numbers (the first part of a uuid4) would be equal.

**Comment by vdbergh** [comment] 2021-09-15 05:57
@ppigazzini Your explanation cannot be correct I think. In fact: if the uuid's are different then so are the worker keys.

Explanation: different uuids that belong to the same user are given a different sequence number in the worker key. So different uuids should always lead to different worker keys.

So I really think there is no bug here. IMHO what happened was that the worker was restarted, but right before restarting it picked up a task, but couldn't complete any games on it.

**Comment by tomtor** [comment] 2021-09-15 06:06
> IMHO what happened was that the worker was restarted, but right before restarting it picked up a task, but couldn't complete any games on it.

But the residual was changing on the killed worker line, while the new worker incremented the number of played games (at 32 of 64 games).

**Comment by vdbergh** [comment] 2021-09-15 06:24
But it is normal that the residual changes even for a dead worker....

BTW: these sequence numbers are really a nuisance. To calculate them one needs a global dictionary UUID_MAP. But of course this dictionary is not preserved under server restarts so it has to be recalculated and the consequences of this are ill defined IMHO. I think for example that the sequence numbers may change after a server restart. 

Personally I would get rid of the sequence numbers. The probability that two workers have the same worker key (with the sequence number omitted) is extremely small (and it would be without serious consequences anyway). So the sequence number is redundant.

Getting rid of sequence numbers would simply the code since then the worker key could simply be computed once in `request_task()`.

**Comment by ppigazzini** [comment] 2021-09-15 07:55
> @ppigazzini Your explanation cannot be correct I think. In fact: if the uuid's are different then so are the worker keys.

@vdbergh this should be a big problem, because my explanation is the same of your :) Read my first post: code is working fine, Tom is confused by new data presentation.

> Explanation: different uuids that belong to the same user are given a different sequence number in the worker key. So different uuids should always lead to different worker keys.

I know, the last month I improved the worker key adding the first group of digit from UUID, see #980

> So I really think there is no bug here. IMHO what happened was that the worker was restarted, but right before restarting it picked up a task, but couldn't complete any games on it.

I fear that the last sentence is wrong :( After the restart the Tom's worker has not played the number of games required to be included in the chi2 computation. In my first post I showed the snippet of code and also copied the updated table after some minutes that show that the new worker has a residuals.

**Comment by ppigazzini** [comment] 2021-09-15 09:45
> But it is normal that the residual changes even for a dead worker....
> 
> BTW: these sequence numbers are really a nuisance. To calculate them one needs a global dictionary UUID_MAP. But of course this dictionary is not preserved under server restarts so it has to be recalculated and the consequences of this are ill defined IMHO. I think for example that the sequence numbers may change6 after a server restart.
> 
> Personally I would get rid of the sequence numbers. The probability that two workers have the same worker key (with the sequence number omitted) is extremely small (and it would be without serious consequences anyway). So the sequence number is redundant.
> 
> Getting rid of sequence numbers would simply the code since then the worker key could simply be computed once in `request_task()`.

I agree.

These are respectively the first test ran with all the workers with `uuid` and the last test ran without workers `uuid` (both date "2013-09-11", now is at test page 4309/4387 )
https://tests.stockfishchess.org/tests/view/523080240ebc5957c3a1cd09
https://tests.stockfishchess.org/tests/view/522dc6d20ebc593dd6bc6efa

DEV is running without the sequence number, the only tests with collision risk should be the very old one.

**Closed** 2021-09-17 08:30 UTC
Labels: question, server
