### ISSUE TITLE
Fishtest no longer builds correctly profiled executables on GCC

### ISSUE THREAD

**Issue by gvreuls** [glinscott/fishtest#952] opened 2021-06-23 17:34 UTC
Since [this stockfish commit](https://github.com/official-stockfish/Stockfish/commit/0171b506ec96e2b8c8fcc7758cd5624ad26c0552) which places the profiling data generated by ``make profile-build`` on GCC compilers in a subdirectory called ``profdir``, the fishtest automatic build process no longer works correctly because the compiler can't find the profiling data during step 3 of the Makefile profile-build process:
```
psqt.cpp: In function ‘Stockfish::PSQT::init()’:
psqt.cpp:131:1: warning: ‘profdir/#home#fishtest#fishtest#worker#tmp01_m8pqd#candirufish-Stockfish-0a0ba70#src#psqt.gcda’ profile count data file not found [-Wmissing-profile]
  131 | } // namespace Stockfish
      | ^
bitbase.cpp: In member function ‘std::_Vector_base<Stockfish::(anonymous namespace)::KPKPosition, std::allocator<Stockfish::(anonymous namespace)::KPKPosition> >::_M_allocate(unsigned long)’:
bitbase.cpp:172:1: warning: ‘profdir/#home#fishtest#fishtest#worker#tmp01_m8pqd#candirufish-Stockfish-0a0ba70#src#bitbase.gcda’ profile count data file not found [-Wmissing-profile]
  172 | } // namespace Stockfish
      | ^

etc.
```

This basically means that most of the stockfish executables running on fishtest for the last few days are not fully optimized (they are of ``make build`` quality).

_Note that this only happens on fishtest._ If you build a profiled stockfish executable by hand you get no warnings, so I suspect it has to do with the way the worker juggles directories during the make process.

**Edit: As discussed in #956 this only happens when the ``ccache`` compiler cache is installed.**

**Comment by vondele** [comment] 2021-06-24 04:15
what's the OS on which this happens, or is it for all?

**Comment by gvreuls** [comment] 2021-06-24 05:59
@vondele My workers are Fedora Linux (fc33) on a 5.12.x kernel. I don't know about other OSes.

**Comment by proukornew** [comment] 2021-06-24 06:32
@gvreuls 
Can u save&share broken binary?
@@ -746,6 +746,7 @@ profile-build: net config-sanity objclean profileclean
	@echo ""
	@echo "Step 2/4. Running benchmark for pgo-build ..."
	$(PGOBENCH) > /dev/null
+	cp $(PGOBENCH) stockfish-broken
	@echo ""
	@echo "Step 3/4. Building optimized executable ..."
	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) objclean

**Comment by gvreuls** [comment] 2021-06-24 06:54
@proukornew I don't know how to do this responsibly because this only happens on fishtest, I can't just edit the Makefile, I'll have to run a test with an edited Makefile which will leave a ``stockfish-broken`` executable on every worker that runs the test.

**Comment by proukornew** [comment] 2021-06-24 08:00
Or instead binary something like this:
cat $(EXE) | hexdump -C | grep -E -B6 "\.gcda"

**Comment by gvreuls** [comment] 2021-06-24 08:32
@proukornew I only have access to the optimized binaries created by ``-fprofile-use=profdir`` in step 3 of the Makefile ``profile-build`` process, the instrumented binaries created by ``-fprofile-generate=profdir`` in step 1 are automatically deleted in step 3 so I can only get to them by running a test with a modified Makefile as explained in my previous post.

Instead I've modified ``games.py`` so it doesn't remove the temporary directory where it compiles its executables so I can see where the .gcda files end up.

Here is a generated warning (which says where it expects the .gcda file):
```
psqt.cpp: In function ‘Stockfish::PSQT::init()’:
psqt.cpp:131:1: warning: ‘profdir/#home#fishtest#fishtest#worker#tmpm4bt28nr#SFisGOD-Stockfish-7f720b9#src#psqt.gcda’ profile count data file not found [-Wmissing-profile]
  131 | } // namespace Stockfish
      | ^
```

Searching the corresponding file from the workers current directory:
```
[fishtest@thaumaturgia worker]$ find tmpm4bt28nr -name *psqt.gcda
tmpm4bt28nr/SFisGOD-Stockfish-7f720b9/src/profdir/#home#fishtest#fishtest#worker#tmpe880ldqh#SFisGOD-Stockfish-def85a7#src#psqt.gcda
```

I think this really looks like the worker getting confused about directories, not the compiler or make.

**Comment by proukornew** [comment] 2021-06-24 08:58
Looks messy:
#home#fishtest#fishtest#worker#tmpe880ldqh#SFisGOD-Stockfish-def85a7#src#psqt.gcda
should be
#home#fishtest#fishtest#worker#tmpe880ldqh#SFisGOD-Stockfish-def85a7#src#profdir#psqt.gcda
What about timestamp?

**Comment by gvreuls** [comment] 2021-06-24 09:10
@proukornew It's even worse, the name of the patch itself gets mangled:

#home#fishtest#fishtest#worker#tmp**e880ldqh**#SFisGOD-Stockfish-**def85a7**#src#psqt.gcda

should be:
#home#fishtest#fishtest#worker#tmp**m4bt28nr**#SFisGOD-Stockfish-**7f720b9**#src#psqt.gcda

I don't understand exactly what you mean by timestamps but I'm quite sure ``tmpm4bt28nr`` is the only temporary directory in the worker's current directory so I'm not looking at the wrong files.

**Comment by proukornew** [comment] 2021-06-24 09:12
@gvreuls , i know, i've pointed on more strange detail

**Comment by ppigazzini** [comment] 2021-06-24 09:38
> I think this really looks like the worker getting confused about directories, not the compiler or make.

The worker code simply call the `make` command. so could be a python problem with the `subprocess.check_call()`. I suppose that you have the problem with both of your workers (python 3.9.2 and python 3.9.5):
https://github.com/glinscott/fishtest/blob/fc0a51cae3085f6c389398a1a31820e319162620/worker/games.py#L418-L435

**Comment by proukornew** [comment] 2021-06-24 11:21
Okay, i've found inconsistency, little later will make patch for fishtest in separate issue with more details.

**Comment by ppigazzini** [comment] 2021-06-24 11:28
@proukornew python 3.3.3 is the older 3.x version running on fishtest. We dropped the python 2.x support (but there are still 3 workers on python 2.x, though).

**Comment by ppigazzini** [comment] 2021-06-25 10:53
Closing.
The problem was caused by `ccache`, see
https://github.com/glinscott/fishtest/issues/956#issuecomment-867859272
https://github.com/glinscott/fishtest/issues/956#issuecomment-867881240

**Closed by ppigazzini** 2021-06-25 10:53 UTC
Labels: bug, worker
