### ISSUE TITLE
Refreshing the browser

### ISSUE THREAD

**Issue by Rocky640** [glinscott/fishtest#134] opened 2018-01-26 15:05 UTC
On Chrome, 
if I refresh, say, at every 5 seconds, 
some tests disappear from the "Active Tests"
only to reappear on the next refresh.

**Comment by ianfab** [comment] 2018-01-26 16:34
Do they completely disappear or are they moved to the pending or finished tests?

**Comment by Rocky640** [comment] 2018-01-26 16:58
It was a running test, and new workers were continuously assigned to the test, and new results were updated. Test is still running and was not interrupted in any manner.

Now that I try to reproduce, it does not happen anymore.

The running test did not moved to "finished test", but maybe to "pending". I cannot tell since my pending tests were hidden when it happens.

It happened with my other browsers too: Firefox, and Internet Explorer (on windows 7)

If I see that again, I will try to make some screen shots.

**Comment by Rocky640** [comment] 2018-01-26 17:05
It just happened again. This time 2 tests disappeared.
Picture 1: 2 tests are missing
![image](https://user-images.githubusercontent.com/8949638/35451350-ea8b3c58-0290-11e8-8249-18ed6bae97d9.png)

Picture 2: after a refresh, the 2 tests reappeared
![image](https://user-images.githubusercontent.com/8949638/35451369-f6544188-0290-11e8-8fa0-437e029d9d54.png)

Picture 3: Showing the workers on my test, no recently added worker.
![image](https://user-images.githubusercontent.com/8949638/35451413-258a1126-0291-11e8-9442-d758a959d49c.png)

**Comment by ianfab** [comment] 2018-01-27 11:53
That indeed looks strange. I can not find a reason from the code why a test is not displayed, because each test always should be in one of the categories pending, failed, active, or finished unless it has been deleted. Maybe @ppigazzini or @Stefano80 could check whether there are error messages in the logs. One could also check whether the browser shows any errors when such strange behavior occurs, e.g., using the developer tools in chrome. Unfortunately I so far could not reproduce the issue.

**Comment by vondele** [comment] 2018-01-31 20:00
I have also observed this (on firefox if this matters).

possibly related... if a test just finished it might appear twice in the 'Finished' list initially.

**Comment by tomtor** [comment] 2018-03-18 11:06
https://github.com/glinscott/fishtest/pull/178 should fix this

The twice in Finished list and inconsistent stopped/colored SPRT results (SPRT is eg < 2.95 but stopped) should have been fixed already with the patches from the last days

**Comment by tomtor** [comment] 2018-04-01 17:51
@Stefano80 @Rocky640 Can we close this? Should be fixed now

**Comment by Stefano80** [comment] 2018-04-01 17:54
I have not noticed this anymore. Closing.

**Closed by Stefano80** 2018-04-01 17:54 UTC
