### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by crossbr** [glinscott/fishtest#423] opened 2019-10-27 18:31 UTC
"Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)"

**Comment by 31m059** [comment] 2019-10-27 20:02
All pages appear to be down, not just the default page (http://tests.stockfishchess.org/tests), but also Actions (http://tests.stockfishchess.org/actions), Users (http://tests.stockfishchess.org/users), etc.

**Comment by Vizvezdenec** [comment] 2019-10-28 07:25
it happened 2-3 times in past days btw

**Comment by 31m059** [comment] 2019-10-28 07:49
Thankfully, it seems to be online now.  :)

**Comment by vondele** [comment] 2019-11-03 21:15
server down again..

**Comment by 31m059** [comment] 2019-11-03 21:56
@vondele Interestingly, live Elo seems to still be online this time (even though it's not receiving any new games, and therefore never updates):
http://tests.stockfishchess.org/html/live_elo.html?5dbf24950ebc5925b64f1965

I wonder if that will help debug the error.

**Comment by crossbr** [comment] 2019-11-03 21:59
@ppigazzini any idea what's causing this?

**Comment by 31m059** [comment] 2019-11-03 23:34
@vondele @crossbr We appear to be back online.

**Comment by ppigazzini** [comment] 2019-11-04 09:31
@crossbr no. Anyway I prefer to use my time to test the new VPS for the fishtest update.

**Comment by vondele** [comment] 2019-11-04 18:15
@ppigazzini  another server down event.

**Comment by ppigazzini** [comment] 2019-11-04 18:19
@vondele rebooted.
Just iron out all the wrinkles on the new OpenVZ7 vps.

**Comment by Alayan-stk-2** [comment] 2019-11-06 15:00
Fishtest down again here, with a failed connection error from my browser.

**Comment by valera-rozuvan** [comment] 2019-11-07 07:03
```
$ ping tests.stockfishchess.org
PING tests.stockfishchess.org (185.83.217.134) 56(84) bytes of data.
^C
--- tests.stockfishchess.org ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 143ms
```

It appears that server is not responding to ICMP echo requests.

**Comment by vondele** [comment] 2019-11-07 13:03
the server was functional for a couple of hours, but seems down now.

**Comment by ppigazzini** [comment] 2019-11-07 13:18
@vondele not reachable with ssh, the ISP informed about the VPS migration from OpenVZ6 to OpenVZ7 after November 6.

**Comment by vondele** [comment] 2019-11-07 14:39
@ppigazzini online again, but with internal error.

**Comment by ppigazzini** [comment] 2019-11-07 14:46
@vondele I'm looking.

**Comment by ppigazzini** [comment] 2019-11-07 15:00
@vondele I loaded on the [dev-server](https://dfts-0.pigazzini.it/tests) the latest db dump (07.11.2019 h 14.08 UTC 0, one hour ago), please check if the db is correct/updated.

**Comment by vondele** [comment] 2019-11-07 15:08
from what I can see this looks OK.

**Comment by 31m059** [comment] 2019-11-07 15:10
@vondele Only the frontpage is down on the main server, these pages still seem to work:

Actions (http://tests.stockfishchess.org/actions)
Users (http://tests.stockfishchess.org/users)
Individual tests (e.g., http://tests.stockfishchess.org/tests/view/5dc274190ebc5904493b16a9)

**Comment by ppigazzini** [comment] 2019-11-07 15:14
The problem is that I got this error with the online db:
```
Starting subprocess with monitor parent
Starting server in PID 597.
serving on http://0.0.0.0:6543
Overview exception: database error: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5dc408e20ebc5902de59148b')
Overview exception: database error: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5dc408e20ebc5902de59148b')
Overview exception: database error: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5dc408e20ebc5902de59148b')
Overview exception: database error: BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('5dc408e20ebc5902de59148b'
...
```

**Comment by 31m059** [comment] 2019-11-07 15:20
So the error is with http://tests.stockfishchess.org/tests/view/5dc408e20ebc5902de59148b?  

I am now getting "refused to connect" errors on all pages, but from a cached version of Actions I have locally, that is the most recently-approved test.  I can no longer see what it is, but @Vizvezdenec submitted it, perhaps he can describe if there was anything unusual about this test...

(not that there necessarily was, I'm not blaming you @Vizvezdenec!)

**Comment by ppigazzini** [comment] 2019-11-07 15:29
@31m059 I stopped pserve to make a backup of the online db and to load it on the dev server: the live migration of the VPS from OpenVZ6 to OpenVZ7 can have corrupted the db. In this case I will try to load the latest backup.

**Comment by ppigazzini** [comment] 2019-11-07 17:12
fishtest is up and running.
The online db was fine when loaded on the [dev-server](https://dfts-0.pigazzini.it/tests), so I deleted the mongo files in /var/db/* and reloaded the dump.

**Comment by ppigazzini** [comment] 2019-11-07 17:28
Collateral effect: the png download is working now :)

**Comment by vondele** [comment] 2019-11-07 17:36
thanks!

**Comment by vondele** [comment] 2019-11-09 19:43
server down again.

**Comment by valera-rozuvan** [comment] 2019-11-09 20:00
http://tests.stockfishchess.org/tests/view/5dc408e20ebc5902de59148b

```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

So now the server responds, but something is wrong.

**Comment by 31m059** [comment] 2019-11-11 20:01
Server completely down again.  `tests.stockfishchess.org refused to connect.`

**Comment by valera-rozuvan** [comment] 2019-11-11 20:53
What's at the core of the downtime? Can we make it restart automatically if a health end-point fails? Maybe move it to k8s - k8s has a built-in mechanism to restart services which break. See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ .

**Comment by d3vv** [comment] 2019-11-11 22:31
this service and database does not state that data should be treated like gold

**Comment by ppigazzini** [comment] 2019-11-11 23:04
> @ppigazzini Server completely down again. `tests.stockfishchess.org refused to connect.` Seems unresponsive to `ping` also...

@31m059 thank you.

**Comment by d3vv** [comment] 2019-11-11 23:10
People who are mired in nosql technologies.. They have nowhere to retreat.. They better get on with their politics and talk - "I don't care just what people say.."

**Comment by ppigazzini** [comment] 2019-11-11 23:21
@tomtor pserve log
```
Starting server in PID 746.
serving on http://0.0.0.0:6543
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
Overview exception: 'ascii' codec can't encode character u'\u0394' in position 633: ordinal not in range(128)
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
[u'missing-input-response']
Overview exception: invalid literal for int() with base 10: "0'"
 Overview exception: invalid literal for int() with base 10: "0'"
Overview exception: invalid literal for int() with base 10: "0'"
Overview exception: invalid literal for int() with base 10: '0"'
Overview exception: invalid literal for int() with base 10: '0"'
Overview exception: invalid literal for int() with base 10: '0"'
Overview exception: invalid literal for int() with base 10: '0--'
Overview exception: invalid literal for int() with base 10: '0--'
Overview exception: invalid literal for int() with base 10: '0--'
```

**Comment by ppigazzini** [comment] 2019-11-11 23:22
@d3vv this is an open source project, volunteers and PRs are welcome.

**Comment by d3vv** [comment] 2019-11-11 23:55
@ppigazzini kidding? All sources about fishtest-clients, isn't? No one knows how the server works (structure and a hash of the hash)

**Comment by d3vv** [comment] 2019-11-12 00:23
@MuliplyByZer01 Can you put it into words w/o emoji? :))

**Comment by Vizvezdenec** [comment] 2019-11-13 20:14
Down again it seems, pings are not going through

**Comment by valera-rozuvan** [comment] 2019-11-14 08:01
What do you do to make the server work again? Restart the failed process? Can we automate it with a cron job - like try to restart it every hour - if it's down?

**Comment by tomtor** [comment] 2019-11-15 10:28
@ppigazzini The server is sometimes very slow on generating the main page. If we look at http://tests.stockfishchess.org/actions we can also see that the "Update user statistics" which used to take always about 30s, sometimes takes many minutes.

Normal time: `19-11-15 07:01:31` (31 seconds)
and slow: `19-11-15 10:19:07` (over 3 minutes).

As I understand we had a change of server infrastructure? The IO-speed is variance is much larger than in the old setup.

**Comment by ppigazzini** [comment] 2019-11-15 11:01
@tomtor correct, the I/O is now slower.
* November 2019 (now):
```bash
$ time (dd if=/dev/zero of=/tmp/test bs=64k count=16k > /dev/null; sync)
16384+0 records in
16384+0 records out
1073741824 bytes (1.1 GB) copied, 3.84712 s, 279 MB/s

real    0m4.100s
user    0m0.009s
sys     0m3.529s
```

* September 2019 (https://github.com/glinscott/fishtest/issues/391#issuecomment-529411249):
```bash
$ time (dd if=/dev/zero of=/tmp/test bs=64k count=16k > /dev/null; sync)
16384+0 records in
16384+0 records out
1073741824 bytes (1.1 GB) copied, 1.70122 s, 631 MB/s

real    0m1.710s
user    0m0.004s
sys     0m1.255s
```

Some facts:
 * The production VPS was hosted on the EOL OpenVZ6 infrastructure with very few active VPSs
 * I rented a test VPS from the same IPS and a couple of weeks ago to test the new OpenVZ7 infrastructure and the I/O was stellar (nearly 1 GB/s), now, after the VPSs mass migration from the EOL infrasctucture, is as fast as the I/O of the production VPS
 * I tried a couple of other IPS offers and the I/O was always way slower than the VPS on OpenVZ6

**Comment by ppigazzini** [comment] 2019-11-15 11:05
@valera-rozuvan I restart the server by hand. I will reinstall the server with Ubuntu 18.04 and new packages.

**Comment by vondele** [comment] 2019-11-15 11:13
I'm not sure it is related, but an observation I made recently is that the number of games played for a test as shown on the main page and on the live_elo pages can be quite different. Sometimes a couple of 100s of games.

**Comment by tomtor** [comment] 2019-11-15 12:40
> 
> 
> I'm not sure it is related, but an observation I made recently is that the number of games played for a test as shown on the main page and on the live_elo pages can be quite different. Sometimes a couple of 100s of games.

Yes, that is caused by the caching of the main page. The fishtest server will only build one main page at a time and cache that for 2 seconds. So when the main page is requested and its age is > 2s then a new MongoDb query will be started to build the main page and the requesting user has to wait for the query to finish. During this period other users will be served the old cached page which is delivered instantly but has outdated info.

In the current setup the mongodb query can take over 30s (used to be about 2s) and as a result it will already have some outdated info when served.

The individual test pages are served from the various caches i added to fishtest the last 2 years, so they are not impacted by a slow MongoDb.

@ppigazzini I assume adding some more RAM would fix this issue so the recent MongoDb data is in the Linux kernel buffer cache.

**Comment by tomtor** [comment] 2019-11-15 21:02
@ppigazzini Main page performance and "update user statistics" is now quite good, did you change something or is the provider infrastructure getting less loaded due to the approaching weekend?

**Comment by ppigazzini** [comment] 2019-11-15 22:08
@tomtor no changes by me.
```bash
$ time (dd if=/dev/zero of=/tmp/test bs=64k count=64k > /dev/null; sync)
65536+0 records in
65536+0 records out
4294967296 bytes (4.3 GB) copied, 12.42 s, 346 MB/s

real    0m13.360s
user    0m0.029s
sys     0m8.375s
```

**Comment by SFisGOD** [comment] 2019-11-16 17:30
@ppigazzini down again

**Comment by glinscott** [comment] 2019-11-16 19:22
It looks like we are overshooting the CPU usage, and the host is shutting down the VPS.

![image](https://user-images.githubusercontent.com/554932/68998146-432c9080-0863-11ea-9cd7-44304aa9b48b.png)

**Comment by glinscott** [comment] 2019-11-16 19:26
I've rebooted the server, but they will shut it down again if we keep hitting the CPU limits.

**Comment by ppigazzini** [comment] 2019-11-16 19:29
@glinscott I already rebooted the server two hours ago. The main page was down?
Anyway it seems that only the main page has problem.

**Comment by crossbr** [comment] 2019-11-16 19:40
Are the CPU load spikes being caused by the completion of a test / start of a new test cycle, or are they unrelated to that?

**Comment by ppigazzini** [comment] 2019-11-16 19:44
@crossbr they should be the hourly backups: mongodb dump, dump compression.

**Comment by snicolet** [comment] 2019-11-17 12:39
If we suppose that the size of the Mongo database is the cause of the slowdowns, what about splitting the database by months? The usual use of the site would only pull data from the last two months (current and previous: this would ensure at least 30 days of history), and there would be a small checkbox (off by default) on each page to pull the pull data as today by looping over all the months since the start of the project.

**Comment by ppigazzini** [comment] 2019-11-17 12:49
@snicolet @tomtor  yesterday wI updated the VPS to Ubuntu18.04 and the new SW stack/configuration.

Some minutes ago mongo was killed for some unknown reasons:

```
~$ sudo journalctl -u mongod
-- Logs begin at Sun 2019-11-17 00:34:42 CET, end at Sun 2019-11-17 13:41:51 CET. --
Nov 17 00:52:16 tests.stockfishchess.org systemd[1]: Started MongoDB Database Server.
Nov 17 02:09:10 tests.stockfishchess.org systemd[1]: Stopping MongoDB Database Server...
Nov 17 02:09:10 tests.stockfishchess.org systemd[1]: Stopped MongoDB Database Server.
Nov 17 02:09:18 tests.stockfishchess.org systemd[1]: Started MongoDB Database Server.
Nov 17 13:16:23 tests.stockfishchess.org systemd[1]: mongod.service: Main process exited, code=killed, status=9/KILL
Nov 17 13:16:23 tests.stockfishchess.org systemd[1]: mongod.service: Failed with result 'signal'.
```

**Comment by snicolet** [comment] 2019-11-17 12:51
Is it possible that the host has an automatic kill for processes using too much CPU or memory?

**Comment by ppigazzini** [comment] 2019-11-17 12:55
@snicolet yes, the official VPS has 0 swap. I rented a  little test VPS with that ISP and the swap is 50% ram. I ask to @glinscott to open a ticket.

**Comment by d3vv** [comment] 2019-11-17 13:03
If anyone has no swap partition or swap-part is too small then it always possible to use a file as swap:

```
# dd if=/dev/zero of=/swapfile bs=2048 count=1048576
# mkswap /swapfile
# swapon /swapfile
```

and add to `/etc/fstab`:

`/swapfile none swap sw 0 0`

**Comment by ppigazzini** [comment] 2019-11-17 13:08
To free some ram I configured the server to use only 1 instance of pserve.
@d3vv thank you, I'll try now.

**Comment by d3vv** [comment] 2019-11-17 13:11
Swap it is very impotent  part into linux for oom-killer actions, so also I used half memory for zswap partitions:

 cat /etc/local.d/zram.start
```
#!/bin/bash

SIZE=512

num_devices=4

until [ $num_devices -eq 0 ]
do
 num_devices=$[$num_devices-1]
 echo $(($SIZE*1024*1024)) > /sys/block/zram$num_devices/disksize
 mkswap /dev/zram$num_devices
 swapon /dev/zram$num_devices -p 10
done
```

4 cause - 4 CPU - it is best for performance..

cat /proc/swaps
```
Filename                                Type            Size    Used    Priority
/dev/md124                              partition       33554364        0      -                                                                                                                                                             1
/dev/zram3                              partition       524284  1536    10
/dev/zram2                              partition       524284  1280    10
/dev/zram1                              partition       524284  1280    10
/dev/zram0                              partition       524284  1280    10
```

**Comment by d3vv** [comment] 2019-11-17 13:19
But it needed to set number of zram-devices on start for kernel:

cat /proc/cmdline
`BOOT_IMAGE=/vmlinuz-4.12.12-gentoo root=/dev/md4 ro md=4,/dev/sda4,/dev/sdb4 zswap.enabled=1 zram.num_devices=4`

it is for heavy-load servers.  zram.num_devices = <number of Real CPU Cores (w/o HT-cores)>

**Comment by ppigazzini** [comment] 2019-11-17 13:27
@d3vv after a little googling I found that OpenVZ usually assign a virtual swap that is RAM based (50% of VPS RAM). For OpenVZ it's a bad practice to add a disk/file swap because it thrashes the host disk sub-system.
Using only 1 pserve instance has freed 30% RAM, so I keep monitored the VPS waiting the IPS's answer.

**Comment by d3vv** [comment] 2019-11-17 13:33
@ppigazzini As I know long time ago it is from virtuozo-settings by admins.. Unfortunately last years I have only practice with XEN and Linux KVM for virtual-instances..

**Comment by ppigazzini** [comment] 2019-11-17 13:48
@d3vv I also have little OpenVZ knowledge. In the last months I tested the multi pserve configuration on the dev server (VPS w/ other IPS) that has a swap of 10 GB disk based, so I never hit the memory wall.
Also on the production server the pserve and mongod processes have a double RAM size because the great number of workers.

**Comment by d3vv** [comment] 2019-11-17 13:57
@ppigazzini Could you explain what is `pserver` mean?
Just in my practice I have used percona mongodb server (best for me):

https://github.com/percona/percona-server-mongodb

But I began to guess that "this pserver" is something else..

**Comment by tomtor** [comment] 2019-11-17 14:02
from https://www.bmc.com/blogs/mongodb-memory-usage-and-management/
> MongoDB, in its default configuration, will use will use the larger of either 256 MB or ½ of (ram – 1 GB) for its cache size.

That looks OK to me, because we would like to fit the last month of tests in the MongoDb cache. 1 Gb for pserve should be sufficient. It would be nice to know the size of 30 days of tests and match the MongoDb cache size.

If an average slot is 200 bytes and we average 100 slots per test and 50 tests each day: 200 * 100 * 50 * 30 => 30 megabyte, so reducing the MongoDb cache (with `cacheSizeGB`) to eg 512 megabyte should allow querying several months efficiently AND restoring the old multi pserv configuration.

> Using only 1 pserve instance has freed 30% RAM

We can raise that later, but I think it is good to reduce it to 1 for now as you did and first lower `cacheSizeGB` to eg 512 megabyte.

@ppigazzini How much RAM has the current server?

**Comment by tomtor** [comment] 2019-11-17 14:03
> Could you explain what is `pserver` mean

That is the Python server which implements the fishtest web server

**Comment by ppigazzini** [comment] 2019-11-17 14:27
@tomtor 5 GB RAM

**Comment by tomtor** [comment] 2019-11-17 14:36
> 5 GB RAM

@ppigazzini Ah, thanks. That's a lot, so MongoDb will try to take 2 gigabyte ((5-1)/2) and will be killed by the kernel if the pserve processes request their fair share. I would estimate that 512 megabyte would be sufficient for MongoDb. 

Currently performance of fishtest is fine BTW, and congratulations on the upgrade to Ubuntu 18.04!

**Comment by d3vv** [comment] 2019-11-17 14:40
Using big `cacheSizeGB` meaning "don't care about unexpected crushes/problems" for performance reason.. In that case you could to use `xfs` with `nobarrier`  option with have no fear :)
In any cases I suggest using swap partition with 25% minimum of RAM on virtual machines too.. It gave a time to be alive if problems persist on main host or guest-host..
zswap also gave a bonus to be online maximum - but it free memory needed..
Also I advise you to pay attention to Percona Solutions..

**Comment by ppigazzini** [comment] 2019-11-17 14:50
@tomtor @d3vv the default `/etc/mongod.conf` has the engines section commented out. I will test on the dev server to avoid a disaster.

```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:
```

**Comment by d3vv** [comment] 2019-11-17 14:56
@ppigazzini yes, it is default configuration for stability reason now.. But it has slow performance..
Also I advice to pay attention to:

https://github.com/DmitryKoterov/cachelrud

**Comment by d3vv** [comment] 2019-11-17 15:24
As for nginx I recommend to set:

`server_tokens   off;`

for hide versa and linux distro for security reason..

I suggest to investigate urls which only GET needed, and which GET+POST needed
And use `limit_except GET {` directive..

**Comment by ppigazzini** [comment] 2019-11-17 16:08
@tomtor @d3vv the current VPS plan doesn't support swap.
Anyway my first priority is to restore the backup process.

**Comment by d3vv** [comment] 2019-11-17 16:29
@ppigazzini Once again, I suggest to use swap from file and if u have low memory use low-size zswap...
This is the way to "get fool" host-machine to escape fall u into it's virtual memory which equal as main system swap in some situations.. Moreover it it nice if ur VDS/VPS on SSD.. In other way if u used xfs-filesystem u can always to use online defrag-proccess for example:

`xfs_fsr /dev/<device>`

where "device" = sda, md1, etc

**Comment by d3vv** [comment] 2019-11-17 17:55
I would to say that no need to rely on an honest distribution of resources when it comes to virtual machines, jail chroots or into Linux Containers.. just keep fighting like:

https://www.youtube.com/watch?v=_OvpzForHyU

**Comment by ppigazzini** [comment] 2019-11-18 10:24
@tomtor @d3vv set `cacheSizeGB: 0.5` and enabled 3 `pserve` instances (and backup process fixed)

**Comment by tomtor** [comment] 2019-11-19 07:03
@ppigazzini For some reason 512MB MongoDb cache performs much worse than 2000MB even when the main page just shows the last 50 tests. The only reason I can think of is that the indices are too big to fit.

**Comment by tomtor** [comment] 2019-11-19 07:22
The query for finished runs in `rundb.py`  around line 216:

    c = self.runs.find(q, skip=skip, limit=limit, sort=[('last_updated', DESCENDING)]) 

The sort would need to inspect ALL tests.

@ppigazzini I wonder when that sort is removed, we might still get recent tests first, but in reverse order of creation instead of update. Could you test removing the sort on the dev server?

If that works then we can do the sort on the retrieved 50 tests in Python to speed it up.

**Comment by ppigazzini** [comment] 2019-11-19 07:31
@tomtor I'm starting commuting. Anyway MongoDB cache raised to 1 GB.

**Comment by ppigazzini** [comment] 2019-11-19 09:40
After the upgrade to Ubuntu the server seems stable, so I close this issue.

**Closed by ppigazzini** 2019-11-19 09:40 UTC

**Comment by snicolet** [comment] 2019-11-19 20:57
It is such a joy to see a speedy server again, thanks everybody!

**Comment by Alayan-stk-2** [comment] 2019-11-20 17:10
I'm getting some "504 Gateway Time-out" when trying to access test pages

**Comment by ppigazzini** [comment] 2019-11-20 17:20
@Alayan-stk-2 we jumped from MongoDB 2.x to MongoDB 4.x, we are debugging an index compatibility problem https://github.com/glinscott/fishtest/pull/434 that slow down MongoDB.

**Comment by ppigazzini** [comment] 2019-11-20 17:38
The VPS went suddenly down. I already wrote to Gary (the VPS owner) to have information.

**Comment by Vizvezdenec** [comment] 2019-11-20 18:29
Everything seems to be up now but older tasks seem to have 0 workers assigning to them

**Comment by Vizvezdenec** [comment] 2019-11-20 18:45
Yes, can be manually fixed with "resetting" them by, for example, modifying total game number.

**Comment by Vizvezdenec** [comment] 2019-11-20 18:59
https://i.imgur.com/oRRF2m3.png
this tasks (and all over them) are not assigned any workers even if workers become free, workers get reassigned to currently running/newer tasks.

**Comment by ppigazzini** [comment] 2019-11-20 21:39
@Vizvezdenec if the problem is still there please open a new issue.

**Comment by Alayan-stk-2** [comment] 2019-11-20 23:32
Getting "502 Bad Gateway" now on the main page...

**Comment by ppigazzini** [comment] 2019-11-20 23:39
@Alayan-stk-2 I stopped fishtest to change some MongoDB indexes not compatible with MongoDB 4.x
