### ISSUE TITLE
Incorrect # finished tests on user pages

### ISSUE THREAD

**Issue by linrock** [glinscott/fishtest#563] opened 2020-04-07 18:20 UTC
If you go to a user's page, it incorrectly shows a large number of finished tests. However, if you go to a high page number, it shows that the actual number of tests is a lot smaller.

---
https://tests.stockfishchess.org/tests/user/protonspring
<img src="https://user-images.githubusercontent.com/208617/78704890-9a96d000-78da-11ea-86bf-5dee0a3f71ad.png" width="300"/>

---
https://tests.stockfishchess.org/tests/user/protonspring?page=1457
<img src="https://user-images.githubusercontent.com/208617/78704920-a8e4ec00-78da-11ea-8c67-734fa5b936f6.png" width="300"/>

**Comment by tomtor** [comment] 2020-04-08 10:01
@linrock Yes, this is a known issue, introduced by various performance optimizations a few months ago when fishtest experienced performance issues.

The issue is caused (and performance is increased) by having an `old_runs` collection and `runs` collection, see eg 

https://github.com/glinscott/fishtest/pull/434

It probably can be fixed with a little bit of additional (MongoDb query) code, at the cost of a slowdown for access to page 1.

**Comment by linrock** [comment] 2020-04-08 17:41
thanks for the info! i find it very surprising that there are performance problems for these pages with only 70k documents between `runs` and `old_runs` since each page only shows a limited number of runs. i'd expect a single `runs` collection to handle millions of documents without issue and without needing to move anything to `old_runs`.

i see you mentioned in https://github.com/glinscott/fishtest/pull/433 that there was a situation where the entire `runs` collection is read, which would definitely be bad. i'll look further into this

**Comment by tomtor** [comment] 2020-04-09 08:17
@linrock  `old_runs` was introduced a few years ago by Gary because fishtest got suddenly slower. I think the working_set of the tables/indices exceeded physical memory at that time. 

Now MongoDb is a much newer version and machine is bigger. `old_runs` should not be needed when queries and indices are all OK.

**Comment by ppigazzini** [comment] 2020-04-10 19:45
@tomtor @linrock should we try to move all data from `old_runs` to `runs` on DEV and run some benches?

**Comment by ppigazzini** [comment] 2020-04-10 19:54
@linrock PROD ran until November 2019 on CentOS 6.10, Python 2.6.6, MongoDB 2.4.4 (not so stable with many data...)

**Comment by linrock** [comment] 2020-04-10 20:46
@ppigazzini yea that sounds good. i'll prepare a PR that switches to using the `runs` collection exclusively. then while using that PR, you could try migrating the data from `old_runs` to `runs` in dev and see how well it works.

**Closed** 2020-04-15 20:09 UTC
Labels: server
