### ISSUE TITLE
SPSA tests have timeouts

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#731] opened 2020-07-25 07:35 UTC
```
Finished game 18 (Base-50fdcc9c94 vs New-50fdcc9c94): 1-0 {White wins by adjudication}
Score of New-50fdcc9c94 vs Base-50fdcc9c94: 6 - 6 - 15  [0.500] 27
Finished game 26 (Base-50fdcc9c94 vs New-50fdcc9c94): 1/2-1/2 {Draw by adjudication}
Score of New-50fdcc9c94 vs Base-50fdcc9c94: 6 - 6 - 16  [0.500] 28
  Task updated successfully in 1.44457s
Elo difference: 0.0 +/- 85.8, LOS: 50.0 %, DrawRatio: 57.1 %
Finished match
Finished match cleanly
2020-07-25 09:11:03.450461 is past end time 2020-07-25 09:11:03.450451
Fetched SPSA parameters successfully in 0.045672s
```

I notice this since a few days. Cutechess does not exit occasionally.

@ppigazzini Any ideas?

**Comment by tomtor** [comment] 2020-07-25 07:43
While it hangs python is 150% busy

I suspect it is introduced with 

https://github.com/glinscott/fishtest/commit/98e846949a39aeb7c741f463b0307edaca5372db

**Comment by tomtor** [comment] 2020-07-25 10:01
When it loops it has a line with length 0 here:

https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L301

and sometimes it exits after some looping due to:

https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L297

**Comment by tomtor** [comment] 2020-07-25 11:46
When I add:

```
    if len(line) == 0 and p.poll() is not None:
       break
```
before

https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L301

it works OK but it is not clear to me why this effect only SPSA.

**Comment by tomtor** [comment] 2020-07-25 12:09
> it works OK but it is not clear to me why this effects only SPSA.

It really is some kind of tricky race condition:

```
if len(line) == 0 and p.poll() is not None:
       print("break")
       break
```

works fine, but removing the `print("break")` makes it hang on occasion...

**Comment by tomtor** [comment] 2020-07-25 13:26
What also seems to work is adding:
```
      return { 'task_alive': True }
```

after
https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L309

@ppigazzini As you see my approach is not very structured ;-)
Any hints/suggestions regarding the root cause is appreciated.

**Comment by ppigazzini** [comment] 2020-07-25 13:35
@tomtor with the STDERR redirection I noted occasionally some void lines in the STDOUT and fixed a bug with https://github.com/glinscott/fishtest/pull/720

**Comment by ppigazzini** [comment] 2020-07-25 13:44
> What also seems to work is adding:
> 
> ```
>       return { 'task_alive': True }
> ```
> 
> after
> https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L309
> 
> @ppigazzini As you see my approach is not very structured ;-)
> Any hints/suggestions regarding the root cause is appreciated.

With windows worker the STDERR is queued after all the macth STODOUT, so return after https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L309 will skip the STDERR processing https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L313-L317

Unfortunately in 2 weeks of tests my workers never hanged :(

**Comment by tomtor** [comment] 2020-07-25 13:57
>  will skip the STDERR processing 

We can rearrange the order of the tests, `Finished Match` test after `option` test?

**Comment by tomtor** [comment] 2020-07-25 13:59
> unfortunately I missed to check for a "soft hang" solved by the timeout

Yes, it fails softly...

**Comment by ppigazzini** [comment] 2020-07-25 14:09
> > will skip the STDERR processing
> 
> We can rearrange the order of the tests, `Finished Match` test after `option` test?

With windows worker we should duplicated the `option` test after the `Finished Match` test like this
https://github.com/glinscott/fishtest/pull/713#issuecomment-653027041

Perhaps the 2 separated pipes for STDOUT and STDERR is a cleaner solution
https://github.com/glinscott/fishtest/pull/713#issuecomment-652439378

I will be online in a couple of hours.

**Comment by ppigazzini** [comment] 2020-07-25 14:54
@tomtor as a safety net we could re set the timeout after a finished match
```python
    if 'Finished match' in line:
      # The following assertion will fail if there are games without result.
      # Does this ever happen?
      assert(num_games_updated==games_to_play)
      print('Finished match cleanly')
      end_time = datetime.datetime.now() + datetime.timedelta(seconds=5)
```

**Comment by tomtor** [comment] 2020-07-25 15:41
> @tomtor as a safety net we could re set the timeout after a finished match
> 
> ```python
>     if 'Finished match' in line:
>       # The following assertion will fail if there are games without result.
>       # Does this ever happen?
>       assert(num_games_updated==games_to_play)
>       print('Finished match cleanly')
>       end_time = datetime.datetime.now() + datetime.timedelta(seconds=5)
> ```

Wouldn't that make things worse, it would hang longer?

**Comment by tomtor** [comment] 2020-07-25 15:44
@ppigazzini please ignore last comment. Yes that would work also but I would prefer understanding the root cause.

**Comment by ppigazzini** [comment] 2020-07-25 17:39
@tomtor I think that the problem is this code from python 2.x:
https://github.com/glinscott/fishtest/blob/c16bc060f6c049fde2a1205f2ca8bfba44bfded2/worker/games.py#L202-L203

This should work:
```python
 for line in iter(out.readline, b''):
   if line:
     queue.put(line) 
```

**Comment by tomtor** [comment] 2020-07-26 07:37
> Anyway we should check if there is a better way with python 3,x

Thanks @ppigazzini !

I am testing your code, it looks good. 
For me no need to search for a better/other way, so I suggest creating/merging a PR.

**Comment by ppigazzini** [comment] 2020-07-27 13:25
@tomtor I pushed the fix in my repo, I will do some tests with the workers (windows, linux, wsl, portable) before opening the PR in fishtest.

**Comment by ppigazzini** [comment] 2020-07-27 20:34
@tomtor I'm not able to replicate the SPSA bug with master (workers: Linux Ubuntu 18.04, WSL Ubuntu 20.04, Windows msys2).
Please share the SPSA run used in your test.

Anyway the Windows workers (WSL ans msys2) are computing some crazy End time `TC limit 3130517932.2826285 End time: 2119-10-10 18:45:01.439100`

**Comment by tomtor** [comment] 2020-07-28 08:49
> Please share the SPSA run used in your test.

See https://github.com/glinscott/fishtest/issues/729#issuecomment-663039163

but ANY SPSA test had the problem for me.

**Comment by ppigazzini** [comment] 2020-07-28 09:18
@tomtor my linux worker has 15 threads (I can raise to 31 using HT), perhaps the ultra short time control mask the problem, I will try with a standard time control.

**Comment by ppigazzini** [comment] 2020-07-28 09:23
@tomtor what distro are you using?

**Comment by tomtor** [comment] 2020-07-28 09:39
@ppigazzini Ubuntu 18.04 on the problem 14 threads worker

**Comment by ppigazzini** [comment] 2020-07-28 13:53
> While it hangs python is 150% busy

@tomtor I missed this info, this should due by cutechess-cli stopped but the python subprocess still opened that fill the stdout/stderr queue with void lines, so you have a zombie that processes the queue until the time out.

Please try if also this solve the bug:
```python
def enqueue_output(out, queue):
  try:
    for line in iter(out.readline, b''):
      queue.put(line)
  except: # Happens on closed file/killed process
    return
  finally:
    out.close()
```

**Comment by tomtor** [comment] 2020-07-28 14:52
@ppigazzini Ok, I am testing your latest code fragment and it does NOT solve the hang:

I get the time exceeded message every time.

**Comment by tomtor** [comment] 2020-07-28 14:55
> I missed this info, this should due by cutechess-cli stopped but the python subprocess still opened

Note that ps shows that while looping/hanging cutechess-cli is defunct:

`24656 pts/1    Z+     0:02 [cutechess-cli] <defunct>`

**Comment by tomtor** [comment] 2020-07-28 15:18
> IMO is wrong to leave opened the stdout in case of exception

```
def enqueue_output(out, queue):
  try:
    for line in iter(out.readline, b''):
      if line:
        queue.put(line)
  except: # Happens on closed file/killed process
    return
  finally:
    out.close()
```

does work too

**Comment by ppigazzini** [comment] 2020-07-28 15:19
@tomtor thank you for testing, I'll update the PR.

**Comment by ppigazzini** [comment] 2020-07-28 22:31
@tomtor results running the following code using different sentinels in `iter`
- `b''` : `full_lines = 30  ;  empty_lines = 50000-250000`
- `''` : `full_lines = 30  ;  empty_lines = 0`

https://docs.python.org/3/library/functions.html#iter
 
```python
def enqueue_output(out, queue):
    full_lines=0
    empty_lines=0
    try:
        for line in iter(out.readline, b''):
#        for line in iter(out.readline, ''):
            if line:
                queue.put(line)
                full_lines += 1
            else:
                empty_lines += 1                
    except:
        return
    finally:
        print('full_lines = {}\nempty_lines = {}'.format(full_lines, empty_lines))
        out.close()
```

**Comment by tomtor** [comment] 2020-07-29 06:02
@ppigazzini Tested your last code and it works ok!

Nice find!

**Comment by ppigazzini** [comment] 2020-07-29 11:43
@tomtor problem finally understood after some studying and testing, see the updated #735 :)

**Comment by vondele** [comment] 2020-07-31 06:13
@ppigazzini nice!

**Closed** 2020-08-03 19:56 UTC
Labels: bug, worker
