### ISSUE TITLE
Consider indices in MongoDB

### ISSUE THREAD

**Issue by xoto10** [glinscott/fishtest#151] opened 2018-03-06 12:34 UTC
There is a possbiilty that slow db queries are part of the cause of current issues on fishtest: https://groups.google.com/d/msg/fishcooking/kA28W9fyCGQ/dhf4bW7GAQAJ

We should evaluate the current indices in the db to see if we can improve them.

e.g. I suspect adding an index on tasks.pending (line 32 rundb.py) might help:
self.runs.ensure_index([('finished', ASCENDING), ('last_updated', DESCENDING)**, ('tasks.pending', ASCENDING)**])

**Comment by noobpwnftw** [comment] 2018-03-06 13:04
1. Is the DB server local?
2. Storage engine used for MongoDB, and it's memory usage.
3. Persistent connections.

**Comment by Stefano80** [comment] 2018-03-06 19:40
@ppigazzini : I think we need you here...

**Comment by ppigazzini** [comment] 2018-03-07 09:56
@noobpwnftw  I'm not an expert of MongoDB
1. the DB is local to the official server (hand made installation), `db.version()` 2.4.4
2. the `db.serverStatus()` does not show any storage engine
3. how can I check the persistent connections?
``` 
db.serverStatus().connections
{ "current" : 5, "available" : 814, "totalCreated" : NumberLong(1025) }
```

**Comment by noobpwnftw** [comment] 2018-03-07 11:00
@ppigazzini 
1. So, I take for this version of MongoDB you might used the default MMAPv1 storage engine, which does not compress any data.

2. How big is the database in files(MongoDB data folder) and how big is the server's memory? Basically for this type of storage engine you need to hold all data plus index inside the memory or it will just cause frequent page faults.

From the connection number you posted, it seems to be using persistent connections already.


I have set up a server to further debug the lag cause.
Can you please try to create those SPSA tests(I don't know how) and reproduce the lag here?
http://112.73.74.24:6543/tests

I have put 50 workers there.

**Comment by ppigazzini** [comment] 2018-03-07 12:05
@noobpwnftw Simply copy an old SPSA test. Write the test as user01 and approve the test as user00. I can not write the test before 3 hours, sorry.

**Comment by xoto10** [comment] 2018-03-07 13:38
I have created a pull request for this: #154

**Comment by noobpwnftw** [comment] 2018-03-07 13:42
I take back what I said about bandwidth is not a problem, it does require quite a lot bandwidth when running tuning tasks.
But I see one major problem with the default deployment:
pserve is single-threaded, I experienced lag even when I have enough bandwidth.
Then I use 4 copies of production.ini and set them on different ports, then use nginx to load balance them, the lag is gone.

Following the guide here,
https://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/deployment/nginx.html

**Comment by ppigazzini** [comment] 2018-03-07 17:24
@noobpwnftw I will try on my test server (http://94.198.98.239/tests) and, if successful, I will set the configuration also on the official server (during the week end). The nginx proxy is useful also to set Let's Encrypt. Thank you!

**Comment by noobpwnftw** [comment] 2018-03-07 18:25
Please also refer to this thread, 
https://groups.google.com/d/msg/fishcooking/kA28W9fyCGQ/UifxWtVPBAAJ

1. It appears that running multiple pserve processes would break the session cookie with current implementation.
2. Excessive information gets uploaded from the client when running SPSA tests.

**Comment by ppigazzini** [comment] 2018-03-08 17:00
@noobpwnftw : @tomtor suggested to use [gunicorn](http://gunicorn.org/) to handle concurrent requests, check here https://github.com/glinscott/fishtest/issues/133

My dev server http://94.198.98.239 is configured with 4 threads, could switch all your workers to test:
- the gunicorn setting
- the connectivity of my ISP

**Comment by tomtor** [comment] 2018-03-08 18:18
@ppigazzini I added my Ryzen 1700x, could you approve:

http://94.198.98.239/tests/view/5aa17bec41b2a16c7d3213e3

**Comment by ppigazzini** [comment] 2018-03-08 20:44
@tomtor I was commuting. Test approved, now I will join also my workers.

**Comment by tomtor** [comment] 2018-03-09 02:40
@ppigazzini The threaded implementation has issues, eg NoTasks  while there are available. The python code has globals so that was to be expected.

Can you test 4 processes instead of 4 threads and restart?

**Comment by tomtor** [comment] 2018-03-09 04:34
@ppigazzini @Stefano80 Given it some thought, multi process won't work either because we need to share sprt/spsa and task state. I will work on thread safety first before we can continue these concurrency tests.

**Comment by ppigazzini** [comment] 2018-03-09 09:27
@tomtor OK, dev server restored to use pserve

**Comment by tomtor** [comment] 2018-03-09 10:06
@ppigazzini @Stefano80 Currently locally testing: https://github.com/glinscott/fishtest/pull/157

If you have the time you could test it on the test server and I will switch my 3 workers, note that especially the SPSA tests show some weird data (look at the graphs in those tests :) 

http://94.198.98.239/tests/view/5aa1f0dd41b2a104f0ecf514

So you should probably restore the MongoDb to a sane state before running new tests...

**Comment by ppigazzini** [comment] 2018-03-09 12:06
@tomtor I will have some spare time to do the tests after the 21:00 CET
Restoring the dev server and the DB requires a couple of commands and 5 minutes

**Comment by Stefano80** [comment] 2018-03-10 19:06
Closing, as the discussion drifted away from the original issue, which was anyway not an issue but a suggestion.

**Closed by Stefano80** 2018-03-10 19:06 UTC
